In [1]:
import numpy as np

### Arrays in Numpy

In [11]:
#Create a 2-D array
x = np.array(((1,5),(3,45)))
x1 = np.array([[1,5],[3,45]]) # <- Different tyoe of nomenclature

In [18]:
print("Vector x :","\n",x)
print("Forma de x:","\n",x.shape)
print("Dimension de x:","\n",x.ndim)
print("Numero de elementos en x:","\n",x.size,"\n")
print("Vector x1 :","\n",x1)
print("Forma de x1:","\n",x1.shape)
print("Dimension de x1:","\n",x1.ndim)
print("Numero de elementos en x1:","\n",x1.size,"\n")

Vector x : 
 [[ 1  5]
 [ 3 45]]
Forma de x: 
 (2, 2)
Dimension de x: 
 2
Numero de elementos en x: 
 4 

Vector x1 : 
 [[ 1  5]
 [ 3 45]]
Forma de x1: 
 (2, 2)
Dimension de x1: 
 2
Numero de elementos en x1: 
 4 



In [19]:
#Create a 3-D array
x = np.array(((1,5,3),(3,45,5),(4,2,3)))
x1 = np.array([[1,5,3],[3,45,5],[4,2,3]]) # <- Different tyoe of nomenclature

In [26]:
#Atributos
print("Vector x :","\n",x)
print("Forma de x:","\n",x.shape)
print("Dimension de x:","\n",x.ndim)
print("Numero de elementos en x:","\n",x.size,"\n")
print("Vector x1 :","\n",x1)
print("Forma de x1:","\n",x1.shape)
print("Dimension de x1:","\n",x1.ndim)
print("Numero de elementos en x1:","\n",x1.size,"\n")

Vector x : 
 [[ 1  5  3]
 [ 3 45  5]
 [ 4  2  3]]
Forma de x: 
 (3, 3)
Dimension de x: 
 2
Numero de elementos en x: 
 9 

Vector x1 : 
 [[ 1  5  3]
 [ 3 45  5]
 [ 4  2  3]]
Forma de x1: 
 (3, 3)
Dimension de x1: 
 2
Numero de elementos en x1: 
 9 



### Vectors in numpy

In [27]:
#Create a vector
V1=np.array((1,5))

In [31]:
print("Vector V1:","\n",V1)
print("Forma de V1:","\n",V1.shape)

Vector V1: 
 [1 5]
Forma de V1: 
 (2,)


In [33]:
#Reshape V1 into a column vector V2
V2=V1.reshape((2,1))
print("Vector V2:","\n",V2)

Vector V2: 
 [[1]
 [5]]


In [34]:
#Reshape V2 back into a column vector V3
V3=V2.reshape((1,2))
print("Vector V3:","\n",V3)

Vector V3: 
 [[1 5]]


## Flatten Vector

In [40]:
#Suma de vectores 
print("Vector V1=",V1)
print("Vector V2=","\n",V2)
print("Resultado de V1+V2 =:","\n",V1+V2)

Vector V1= [1 5]
Vector V2= 
 [[1]
 [5]]
Resultado de V1+V2 =: 
 [[ 2  6]
 [ 6 10]]


In [41]:
#Flatten vector V2 into V4
V4=V2.flatten()
print("Vector V2:","\n",V2)
print("Flattened vector V4=","\n",V4)

Vector V2: 
 [[1]
 [5]]
Flattened vector V4= 
 [1 5]
