In [4]:
import sys
import numpy as np #mathematical library 

print ("Python: {}" .format(sys.version))
print ("NumPy: {}" .format(np.__version__))

Python: 3.7.4 (default, Aug 13 2019, 20:35:49) 
[GCC 7.3.0]
NumPy: 1.17.2


In [7]:
#Definiendo un escalar
x = 6 
print ("El valor de x =",x )

El valor de x = 6


In [26]:
#Definiendo un vector 
x = np.array((1,2,3))
print ("El vector es x :", x)

El vector es x : [1 2 3]


In [18]:
print ("La dimension del vector:",format(x.shape))
print ("El tamaño del vector:" ,format(x.size))

La dimension del vector: (3,)
El tamaño del vector: 3


In [29]:
#Definiendo una matriz 
x=np.matrix([[1,2,3],[4,5,6],[7,8,9]])
print("La matriz x:",x)
print(" ")
x

La matriz x: [[1 2 3]
 [4 5 6]
 [7 8 9]]
 


matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [31]:
print("La dimension de la matriz es:", format(x.shape))
print("El tamaño de la matriz es:", format(x.size))

La dimension de la matriz es: (3, 3)
El tamaño de la matriz es: 9


In [39]:
#Definir una matriz de una dimension dada
x=np.zeros((3,3))
print("La matriz x:",x)
print("") 
y=np.ones((5,5))
print("La matriz y:",y)
print("")

La matriz x: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

La matriz y: [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]



In [40]:
print("La dimension de la matriz X es:", format(x.shape))
print("El tamaño de la matriz X es:", format(x.size))
print("La dimension de la matriz Y es:", format(y.shape))
print("El tamaño de la matriz Y es:", format(y.size))

La dimension de la matriz X es: (3, 3)
El tamaño de la matriz X es: 9
La dimension de la matriz Y es: (5, 5)
El tamaño de la matriz Y es: 25


In [42]:
#Definiendo tensor
x = np.ones((3,3,3))
#print("El tensor x es:",x)
x
#El punto final del digito indica que son valores de punto flotante "float values"

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [43]:
print("La dimension del Tensor X es:", format(x.shape))
print("El tamaño del Tensor X es:", format(x.size))

La dimension del Tensor X es: (3, 3, 3)
El tamaño del Tensor X es: 27


In [47]:
#indexing 
A = np.ones((5,5), dtype=int)
print ("",A)

 [[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [50]:
#indexacion comienza en 0 
A[0,1]=2
print ("",A)

 [[1 2 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [51]:
A[:,0]=3
print("",A)

 [[3 2 1 1 1]
 [3 1 1 1 1]
 [3 1 1 1 1]
 [3 1 1 1 1]
 [3 1 1 1 1]]


In [54]:
A[:,:]=5
#print("",A)
print (A)

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


In [58]:

A = np.zeros((5,5,5),dtype=np.int)
print(A)
A[:,:]=1
print(A)

[[[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]]
[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


In [59]:
#Agregar dimensiones mediante indexacion 
A = np.ones((5,5,5),dtype=np.int)
#Asignar a la primer fila un nuevo valor 
A[:,0,0]=6
print(A)

[[[6 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[6 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[6 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[6 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[6 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


In [68]:
#operaciones con matrices
A = np.matrix([[2,3],[4,5]])
B = np.ones((2,2),dtype=np.int)
print("La matriz A es:",A)
print("La matriz B es:",B)

La matriz A es: [[2 3]
 [4 5]]
La matriz B es: [[1 1]
 [1 1]]


In [70]:
C = A+B
print("A + B =")
print(C)

A + B =
[[3 4]
 [5 6]]


In [71]:
C=A-B
print("A - B =")
print (C)

A-B =
[[1 2]
 [3 4]]


In [72]:
C=A*B
print("A * B =")
print(C)


A * B =
[[5 5]
 [9 9]]


In [78]:
#la transpuesta de la matriz
A=np.array(range(9))
print("EL vector renglon A es :",A)
A=A.reshape(3,3)
print("La matriz A es :", A)
B = A.T
print("La transpuesta de A es:")
print (B)
C=B.T
print("La transpuesta de la transpuesta es la original:")
print(C)


EL vector renglon A es : [0 1 2 3 4 5 6 7 8]
La matriz A es : [[0 1 2]
 [3 4 5]
 [6 7 8]]
La transpuesta de A es:
[[0 3 6]
 [1 4 7]
 [2 5 8]]
La transpuesta de la transpuesta es la original:
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [86]:
A = np.array(range(10))
print(A)
print("La dimension es :",A.size)
print ("")
A = A.reshape(2,5)
print (A)
print("La dimension es :",A.shape)
B=A.T
print("Transponiendo:")
print(B)
print("La dimension es :",B.shape)

[0 1 2 3 4 5 6 7 8 9]
La dimension es : 10

[[0 1 2 3 4]
 [5 6 7 8 9]]
La dimension es : (2, 5)
Transponiendo:
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]
La dimension es : (5, 2)


In [91]:
#Tensores 
A = np.ones((3,3,3,3,3,3,3,3,3,3))
print(A.shape)
print("Su dimension es :", len(A.shape))
print(A.size)

(3, 3, 3, 3, 3, 3, 3, 3, 3, 3)
Su dimension es : 10
59049
