In [1]:
import numpy as np

In [2]:
A = np.ones((3,3),dtype=int)

In [3]:
print(A)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [10]:
B = np.matrix([[1,2,3],[4,5,6],[7,8,9]])

In [8]:
C = A*B 

In [9]:
print(C)

[[12 15 18]
 [12 15 18]
 [12 15 18]]


In [16]:
B = np.matrix([[1,0,0],[0,1,0],[0,0,1]])

In [18]:
print(A)
print("")
print(B)
print("A*B=")
C=A*B
print(C)

[[1 1 1]
 [1 1 1]
 [1 1 1]]

[[1 0 0]
 [0 1 0]
 [0 0 1]]
A*B=
[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [19]:
A=np.matrix([[1,2,3],[4,5,6],[7,8,9]])

In [20]:
print(A)
print("")
print(B)
print("A*B=")
C=A*B
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 0 0]
 [0 1 0]
 [0 0 1]]
A*B=
[[1 2 3]
 [4 5 6]
 [7 8 9]]
